[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.build]
includes = [
    'src/wexample_wex_addon_dev_css/*',
]
package-dir = "src"

[[tool.pdm.build.packages]]
include = "wexample_wex_addon_dev_css"
from = "src"

[project]
name = "wexample-wex-addon-dev-css"
version = "0.0.2"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2,<3",
    "wexample-wex-core==6.0.44",
]

[project.optional-dependencies]
dev = [
    "pytest",
]
